# Generated by Django 5.1.1 on 2024-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('azan', models.CharField(max_length=10)),
                ('prayer', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
    ]
