# Generated by Django 5.1.1 on 2024-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('road', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('days_active', models.CharField(max_length=50)),
            ],
        ),
    ]
