# Generated by Django 5.1.1 on 2024-09-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='road',
            new_name='lga',
        ),
    ]
