# Generated by Django 5.1.1 on 2024-09-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
