# Generated by Django 5.1.1 on 2024-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
