# Generated by Django 5.1.1 on 2024-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_service_days_alter_service_end_alter_service_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
