# Generated by Django 5.1.1 on 2024-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('zoom', models.FloatField()),
            ],
        ),
    ]
