# Generated by Django 5.1.1 on 2024-09-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_mosque_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='from_zoom',
            field=models.BooleanField(default=False),
        ),
    ]
