# Generated by Django 5.1.1 on 2024-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_mosque_from_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slugger',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
