# Generated by Django 5.1.1 on 2024-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_event_slugger'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
