# Generated by Django 5.1.1 on 2024-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
